# Generated by Django 5.0.2 on 2024-04-16 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0002_rename_type_produit_type_prod'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='type_prod',
            new_name='type',
        ),
    ]
