# Generated by Django 5.0.2 on 2024-05-11 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0007_commande_qte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modificationquantitestock',
            name='date_modification',
        ),
    ]
